server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:gtandu/project-watcher-config.git
          clone-on-start: true
          default-label: master
  security:
    user:
      name: root
      password: pwdtest
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
